name: Laravel Auth Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: Laravel Authentication Image Build
        run: |
          docker build -t mostafaroshdy1/laravel-auth .
      - name: Laravel Authentication Image Push
        run: |
          docker push mostafaroshdy1/laravel-auth
          
